// export interface IWidget {
//     title: string,
//     content: string
// }

export const Widgets = [
    {
        title: "San Francisco 49ers@ Seattle Seahawks",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american - football" data-q4="6ec3f0aa-c85c-458e-bee1-d97204f644e1"><span>The San Francisco 49ers have a forecast 51% chance to win against The Seattle Seahawks with a spread of -0.5/0.5 and an over/under of 40.5. The San Francisco 49ers are 1 - 0 against The Seattle Seahawks in the 2022-23 Season.</span>&mdash; <em>Thursday, December 15th San Francisco 49ers @ Seattle Seahawks</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Indianapolis Colts@ Minnesota Vikings",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="bb380342-d765-4e13-8dd9-df3f388b18da"><span>The Minnesota Vikings have a forecast 73% chance to win against The Indianapolis Colts with a spread of -6.5/6.5 and an over/under of 48.0. The Minnesota Vikings are 0 - 0 against The Indianapolis Colts in the 2022-23 Season.</span>&mdash; <em>Saturday, December 17th Indianapolis Colts @ Minnesota Vikings</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Baltimore Ravens@ Cleveland Browns",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="a73cce5f-2718-40cd-a210-5ce07d821f3c"><span>The Cleveland Browns have a forecast 69% chance to win against The Baltimore Ravens with a spread of -5.5/5.5 and an over/under of 36.0. The Cleveland Browns are 0 - 1 against The Baltimore Ravens in the 2022-23 Season.</span>&mdash; <em>Saturday, December 17th Baltimore Ravens @ Cleveland Browns</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    },
     {
        title: "Miami Dolphins@ Buffalo Bills",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="af5edc28-854b-4e02-a163-950e329f57c5"><span>The Buffalo Bills have a forecast 81% chance to win against The Miami Dolphins with a spread of -10.0/10.0 and an over/under of 44.0. The Buffalo Bills are 0 - 1 against The Miami Dolphins in the 2022-23 Season.</span>&mdash; <em>Saturday, December 17th Miami Dolphins @ Buffalo Bills</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Philadelphia Eagles@ Chicago Bears",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="786dcf78-8de3-42ad-a7b3-1b5cc657a340"><span>The Philadelphia Eagles have a forecast 72% chance to win against The Chicago Bears with a spread of -7.0/7.0 and an over/under of 45.5. The Philadelphia Eagles are 0 - 0 against The Chicago Bears in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th Philadelphia Eagles @ Chicago Bears</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Dallas Cowboys@ Jacksonville Jaguars",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="d547d367-0239-40fd-8d7d-a8cd076bc639"><span>The Dallas Cowboys have a forecast 56% chance to win against The Jacksonville Jaguars with a spread of -2.0/2.0 and an over/under of 45.0. The Dallas Cowboys are 0 - 0 against The Jacksonville Jaguars in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th Dallas Cowboys @ Jacksonville Jaguars</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>
`
    }, {
        title: "Detroit Lions@ New York Jets",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="dbcc29f1-4cad-4045-a52c-224ae67cb3b1"><span>The New York Jets have a forecast 59% chance to win against The Detroit Lions with a spread of -3.0/3.0 and an over/under of 42.5. The New York Jets are 0 - 0 against The Detroit Lions in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th Detroit Lions @ New York Jets</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Atlanta Falcons@ New Orleans Saints",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="fd84e0c0-4205-4cbe-aea8-ea62e5d6f4fe"><span>The New Orleans Saints have a forecast 75% chance to win against The Atlanta Falcons with a spread of -7.0/7.0 and an over/under of 43.0. The New Orleans Saints are 1 - 0 against The Atlanta Falcons in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th Atlanta Falcons @ New Orleans Saints</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Kansas City Chiefs@ Houston Texans",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="3742d8c9-420b-468c-a031-b202872f7d94"><span>The Kansas City Chiefs have a forecast 88% chance to win against The Houston Texans with a spread of -12.0/12.0 and an over/under of 46.5. The Kansas City Chiefs are 0 - 0 against The Houston Texans in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th Kansas City Chiefs @ Houston Texans</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Arizona Cardinals@ Denver Broncos",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="22bb160f-ad31-4dfe-a8d7-2dda1089e3fa"><span>The Denver Broncos have a forecast 69% chance to win against The Arizona Cardinals with a spread of -5.5/5.5 and an over/under of 35.5. The Denver Broncos are 0 - 0 against The Arizona Cardinals in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th Arizona Cardinals @ Denver Broncos</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "New England Patriots@ Las Vegas Raiders",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="0721478e-9590-48f8-95c4-6a2b6017fd1f"><span>The Las Vegas Raiders have a forecast 57% chance to win against The New England Patriots with a spread of -2.5/2.5 and an over/under of 42.5. The Las Vegas Raiders are 0 - 0 against The New England Patriots in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th New England Patriots @ Las Vegas Raiders</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Cincinnati Bengals@ Tampa Bay Buccaneers",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="544b3c16-9fd9-40a5-98c1-22436a0470fc"><span>The Cincinnati Bengals have a forecast 53% chance to win against The Tampa Bay Buccaneers with a spread of -1.0/1.0 and an over/under of 41.0. The Cincinnati Bengals are 0 - 0 against The Tampa Bay Buccaneers in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th Cincinnati Bengals @ Tampa Bay Buccaneers</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }, {
        title: "Tennessee Titans@ Los Angeles Chargers",
        content: `<blockquote class="q4-game" data-detail="true" data-color-background="01005F" data-color-text="FFFFFF" data-color-high="FFFFFF" data-color-medium="FFFFFF" data-color-low="FFFFFF" data-sport="american-football" data-q4="35757df2-51a8-4dad-aa4f-a48c25deb7c1"><span>The Los Angeles Chargers have a forecast 69% chance to win against The Tennessee Titans with a spread of -5.5/5.5 and an over/under of 46.0. The Los Angeles Chargers are 0 - 0 against The Tennessee Titans in the 2022-23 Season.</span>&mdash; <em>Sunday, December 18th Tennessee Titans @ Los Angeles Chargers</em></blockquote><script src="https://api.quarter4.io/american-football/widget/embed/161b7887-e6c0-4445-ba31-658e37076e3f/v1.js" charset="utf-8"></script>`
    }
];
